{{- if and .Values.dataservice.enabled (not .Values.standalone.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus-ha.dataservice.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
{{- if .Values.dataservice.service.labels }}
{{ toYaml .Values.dataservice.service.labels | indent 4 }}
{{- end }}
    component: "dataservice"
{{- with .Values.dataservice.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  {{- if .Values.dataservice.service.clusterIP }}
  clusterIP: {{ .Values.dataservice.service.clusterIP }}
  {{- end }}
  ports:
    - name: dataservice
      port: {{ .Values.dataservice.service.port }}
      protocol: TCP
      targetPort: dataservice
  selector:
{{ include "milvus-ha.matchLabels" . | indent 4 }}
    component: "dataservice"
{{- end }}
