{{- if and .Values.master.enabled (not .Values.standalone.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus-ha.master.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
{{- if .Values.master.service.labels }}
{{ toYaml .Values.master.service.labels | indent 4 }}
{{- end }}
    component: "master"
{{- with .Values.master.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  {{- if .Values.master.service.clusterIP }}
  clusterIP: {{ .Values.master.service.clusterIP }}
  {{- end }}
  ports:
    - name: master
      port: {{ .Values.master.service.port }}
      protocol: TCP
      targetPort: master
  selector:
{{ include "milvus-ha.matchLabels" . | indent 4 }}
    component: "master"
{{- end }}
