{{- if and .Values.pulsar.enabled (not .Values.standalone.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus-ha.pulsar.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "pulsar"
spec:
  replicas: {{ .Values.pulsar.replicas }}
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: "pulsar"
  template:
    metadata:
      labels:
{{ include "milvus-ha.matchLabels" . | indent 8 }}
        component: "pulsar"
    spec:
      {{- if .Values.image.pulsar.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pulsar.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: pulsar
        image: "{{ .Values.image.pulsar.repository }}:{{ .Values.image.pulsar.tag }}"
        imagePullPolicy: {{ .Values.image.pulsar.pullPolicy }}
        command: ["bin/pulsar", "standalone"]
        {{- if .Values.pulsar.extraEnv }}
        env:
          {{- toYaml .Values.pulsar.extraEnv | nindent 10 }}
        {{- end }}
        ports:
          - name: pulsar
            containerPort: 6650
            protocol: TCP
        resources:
          {{- toYaml .Values.pulsar.resources | nindent 10 }}

      {{- with .Values.pulsar.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pulsar.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pulsar.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
