{{- if and (not .Values.pulsar.enabled) (not .Values.standalone.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus-ha.pulsar.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
{{- if .Values.pulsarStandalone.service.labels }}
{{ toYaml .Values.pulsarStandalone.service.labels | indent 4 }}
{{- end }}
    component: "pulsar"
{{- with .Values.pulsarStandalone.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  {{- if .Values.pulsarStandalone.service.clusterIP }}
  clusterIP: {{ .Values.pulsarStandalone.service.clusterIP }}
  {{- end }}
  ports:
    - name: pulsar
      port: {{ .Values.pulsarStandalone.service.port }}
      protocol: TCP
      targetPort: pulsar
  selector:
{{ include "milvus-ha.matchLabels" . | indent 4 }}
    component: "pulsar"
{{- end }}
