{{- if and .Values.queryservice.enabled (not .Values.standalone.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus-ha.queryservice.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
{{- if .Values.queryservice.service.labels }}
{{ toYaml .Values.queryservice.service.labels | indent 4 }}
{{- end }}
    component: "queryservice"
{{- with .Values.queryservice.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  {{- if .Values.queryservice.service.clusterIP }}
  clusterIP: {{ .Values.queryservice.service.clusterIP }}
  {{- end }}
  ports:
    - name: queryservice
      port: {{ .Values.queryservice.service.port }}
      protocol: TCP
      targetPort: queryservice
  selector:
{{ include "milvus-ha.matchLabels" . | indent 4 }}
    component: "queryservice"
{{- end }}
