{{- if .Values.servicemonitor.enabled }}

{{- if .Values.standalone.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.standalone.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "standalone"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: standalone
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.datanode.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.datanode.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "datanode"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: datanode
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.dataCoordinator.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.data-coordinator.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "data-coordinator"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: data-coordinator
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.indexnode.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.indexnode.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "indexnode"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: indexnode
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.indexCoordinator.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.index-coordinator.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "index-coordinator"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: index-coordinator
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.rootCoordinator.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.root-coordinator.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "root-coordinator"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: root-coordinator
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.proxynode.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.proxynode.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "proxynode"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: proxynode
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.querynode.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.querynode.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "querynode"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: querynode
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.queryCoordinator.enabled (not .Values.standalone.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus-ha.query-coordinator.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "query-coordinator"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: query-coordinator
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

{{- end }}