dependencies:
- name: etcd
  version: 5.5.0
  repository: https://charts.bitnami.com/bitnami
  condition: etcd.enabled
  tags:
    - etcd
- name: minio
  version: 8.0.9
  repository: https://helm.min.io
  condition: minio.enabled
  tags:
    - minio
